<?php

$title = 'Supprimer un chantier';
$url   = $this->url('chantier', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Voulez-vous supprimer le chantier 
    <strong><?= $this->escapeHtml($chantier->codechantier) ?></strong> du client
    <strong><?= $this->escapeHtml($chantier->client) ?></strong>?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $album->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Oui" />
    <input type="submit" class="btn btn-success" name="del" value="Non" />
</div>
</form>