<?php
$title = 'Liste des chantiers';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('chantier', ['action' => 'add']) ?>">Ajouter un chantier</a>
</p>

<table class="table">
<tr>
    <th>Nom</th>
    <th>Lieu</th>
    <th>Foret</th>
    <th>Client</th>
    <th>Code chantier</th>
    <th>Debut</th>
    <th>Fin</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($chantiers as $chantier) : ?>
    <tr>
        <td><?= $this->escapeHtml($chantier->nom) ?></td>
        <td><?= $this->escapeHtml($chantier->lieu) ?></td>
        <td><?= $this->escapeHtml($chantier->foret) ?></td>
        <td><?= $this->escapeHtml($chantier->client) ?></td>
        <td><?= $this->escapeHtml($chantier->codechantier) ?></td>
        <td><?= $this->escapeHtml($chantier->debut) ?></td>
        <td><?= $this->escapeHtml($chantier->fin) ?></td>
        <td>
            <a href="<?= $this->url('chantier', ['action' => 'edit', 'id' => $chantier->id]) ?>">Modifier</a>
            <a href="<?= $this->url('chantier', ['action' => 'delete', 'id' => $chantier->id]) ?>">Supprimer</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>